apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ramkumar93-poi-map-app-dev
  annotations:
    argocd/app-name: ramkumar93-poi-map-app-dev
    backstage.io/kubernetes-id: ramkumar93-poi-map-app
    backstage.io/kubernetes-namespace: ramkumar93
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/ramkumar93-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/ramkumar93/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/ramkumar93/deployments/ramkumar93-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/ramkumar93-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://ramkumar93-poi-map-app-ramkumar93.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ramkumar93"
  system: workshop-system-ramkumar93
  consumesApis:
    - gateway-api-ramkumar93
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ramkumar93
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ramkumar93"
